from OpenGL.GL import *

UNIFORM_TEX = 0
UNIFORM_FLOAT = 1
UNIFORM_VEC2 = 2
UNIFORM_VEC3 = 3
UNIFORM_VEC4 = 4
UNIFORM_INT = 5

GL_TEXTURES = [GL_TEXTURE0, GL_TEXTURE1, GL_TEXTURE2, GL_TEXTURE3, GL_TEXTURE4, GL_TEXTURE5, GL_TEXTURE6, GL_TEXTURE7, GL_TEXTURE8, GL_TEXTURE9, GL_TEXTURE10, GL_TEXTURE11]

UNIFORM_MAP = {
    UNIFORM_TEX: glUniform1i,
    UNIFORM_FLOAT: glUniform1f,
    UNIFORM_INT: glUniform1i,
    UNIFORM_VEC2: glUniform2f,
    UNIFORM_VEC3: glUniform3f,
    UNIFORM_VEC4: glUniform4f,
}
